### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [icejo/prj-rev-bwfs-dasmoto#4]
Grade: **Meets Expectations**

Overall, this project is working great. I really like how consistent you were with the HTML indentation as this helps understand which elements are associated with which section on the page. A couple things I would change is to make sure to link your CSS so it works on anyone elses computer who might download your project and filling in those alt attributes so we can give our users a text descriptor of the image. Next steps, I would look into learning about media queries in an effort to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries 

Nicely done!

**Comment by icejo** [comment]
Thanks :)
